kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: masterservice-operator
subjects:
- kind: ServiceAccount
  name: masterservice-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: masterservice-operator
  apiGroup: rbac.authorization.k8s.io
