apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterservice-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: masterservice-operator
  template:
    metadata:
      labels:
        name: masterservice-operator
    spec:
      serviceAccountName: masterservice-operator
      containers:
        - name: masterservice-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - masterservice-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "masterservice-operator"
