// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterService) DeepCopyInto(out *MasterService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterService.
func (in *MasterService) DeepCopy() *MasterService {
	if in == nil {
		return nil
	}
	out := new(MasterService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MasterService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterServiceCallback) DeepCopyInto(out *MasterServiceCallback) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterServiceCallback.
func (in *MasterServiceCallback) DeepCopy() *MasterServiceCallback {
	if in == nil {
		return nil
	}
	out := new(MasterServiceCallback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterServiceList) DeepCopyInto(out *MasterServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MasterService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterServiceList.
func (in *MasterServiceList) DeepCopy() *MasterServiceList {
	if in == nil {
		return nil
	}
	out := new(MasterServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MasterServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterServiceSpec) DeepCopyInto(out *MasterServiceSpec) {
	*out = *in
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
	out.Callback = in.Callback
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterServiceSpec.
func (in *MasterServiceSpec) DeepCopy() *MasterServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MasterServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterServiceStatus) DeepCopyInto(out *MasterServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterServiceStatus.
func (in *MasterServiceStatus) DeepCopy() *MasterServiceStatus {
	if in == nil {
		return nil
	}
	out := new(MasterServiceStatus)
	in.DeepCopyInto(out)
	return out
}
